pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-ssh
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: SSH
  desc: Execute commands on a remote host through SSH
  type: deploy
  image: plugins/drone-ssh
  labels:
    - deploy
    - ssh
